### ISSUE TITLE
训练失败提示 annotation file format <class 'list'> not supported

### ISSUE THREAD

**Issue by juzhitao** [edvardHua/PoseEstimationForMobile#25]
训练失败提示 annotation file format <class 'list'> not supported，请帮忙看下什么原因

ju@coolpad-ThinkStation-P310:/xjuzhitao/py/PoseEstimationForMobile/training$ python3 src/train.py experiments/mv2_cpm.cfg 
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
BASE_PATH, json_filename====== /xjuzhitao/py/PoseEstimationForMobile/training/dataset ai_challenger_train.json
loading annotations into memory...
Traceback (most recent call last):
  File "src/train.py", line 220, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "src/train.py", line 112, in main
    input_image, input_heat = get_train_input(params['batchsize'], params['max_epoch'])
  File "src/train.py", line 32, in get_train_input
    train_ds = get_train_dataset_pipline(batch_size=batchsize, epoch=epoch, buffer_size=100)
  File "/xjuzhitao/py/PoseEstimationForMobile/training/src/dataset.py", line 101, in get_train_dataset_pipline
    return _get_dataset_pipline(TRAIN_JSON, batch_size, epoch, buffer_size, )
  File "/xjuzhitao/py/PoseEstimationForMobile/training/src/dataset.py", line 77, in _get_dataset_pipline
    join(BASE_PATH, json_filename)
  File "/xjuzhitao/py/PoseEstimationForMobile/training/src/pycocotools/coco.py", line 85, in __init__
    assert type(dataset)==dict, 'annotation file format {} not supported'.format(type(dataset))
AssertionError: annotation file format <class 'list'> not supported

my mv2_cpm.cfg:
[Train]
model: 'mv2_cpm'
checkpoint: '/xjuzhitao/py/PoseEstimationForMobile/checkpoint/'
datapath: '/xjuzhitao/py/PoseEstimationForMobile/training/dataset'
imgpath: '/xjuzhitao/py/PoseEstimationForMobile/training/imgpath/'
visible_devices: '1'
multiprocessing_num: 16
max_epoch: 1000
lr: '0.001'
batchsize: 16
decay_rate: 0.95
input_width: 192
input_height: 192
n_kpoints: 14
scale: 2
identify_occlusion: False
modelpath: '/xjuzhitao/py/PoseEstimationForMobile/model/'
logpath: '/xjuzhitao/py/PoseEstimationForMobile/log/'
num_train_samples: 25000
per_update_tensorboard_step: 500
per_saved_model_step: 2000
pred_image_on_tensorboard: False

dataset:
/xjuzhitao/py/PoseEstimationForMobile/training/dataset/train
/xjuzhitao/py/PoseEstimationForMobile/training/dataset/valid
/xjuzhitao/py/PoseEstimationForMobile/training/dataset/ai_challenger_train.json
/xjuzhitao/py/PoseEstimationForMobile/training/dataset/ai_challenger_valid.json

**Comment by juzhitao** [comment]
anybody have the same issue? please help

**Comment by edvardHua** [comment]
It seem the data type mismatch. You need to debug it by yourself.

**Comment by mmiirroo** [comment]
@edvardHua  the json files of AIchallenger are list ([]), but I check dataset.py, find that it is coco format
I should transform AIChanllenger's json to coco format?
