### ISSUE TITLE
error occurs when convert ckpt to frozen pb.

### ISSUE THREAD

**Issue by crsailing** [edvardHua/PoseEstimationForMobile#8]
Hi, when I convert ckpt to frozen pb using the ckpt you provide, error happened!
Here is the log information.

2018-06-27 19:45:15.060637: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-06-27 19:45:15.169085: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-06-27 19:45:15.169470: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
name: GeForce GTX 1070 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:01:00.0
totalMemory: 7.93GiB freeMemory: 7.06GiB
2018-06-27 19:45:15.169484: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2018-06-27 19:45:15.338374: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-06-27 19:45:15.338418: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 
2018-06-27 19:45:15.338425: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N 
2018-06-27 19:45:15.338564: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6819 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1070 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "./training/src/gen_frozen_pb.py", line 37, in <module>
    saver = tf.train.Saver()
  File "/home/xxxx/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1338, in __init__
    self.build()
  File "/home/xxxx/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1347, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/xxxx/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1372, in _build
    raise ValueError("No variables to save")
ValueError: No variables to save

**Comment by edvardHua** [comment]
@crsailing Can you give the values of argument you set in `gen_forzen_pb.py` ?

**Comment by crsailing** [comment]
I have found which caused the error.
```
python3 src/gen_frozen_pb.py \
--checkpoint=<release/ckpt>/model-29000 --output_graph=<release>/model-xxx.pb \
--size=224 --model=**mv2_cpm_2**
```
`mv2_cpm_2`should be `mv2_cpm`

**Comment by caiya55** [comment]
Is there any ckpt provided in the repository ?
